<?php

namespace App\Config;

if (class_exists(__NAMESPACE__ . '\\EnrollmentV2Masters', false)) {
    return;
}

use CodeIgniter\Config\BaseConfig;

class EnrollmentV2Masters extends BaseConfig
{
    /**
     * Canonical master data and synonym maps used across the enrollment v2 stack.
     *
     * @var array<string,mixed>
     */
    public array $data = [
        'planOptions' => [
            ['id' => 1, 'code' => 'OPTION_1', 'label' => 'Option-1'],
            ['id' => 2, 'code' => 'OPTION_2', 'label' => 'Option-2'],
            ['id' => 3, 'code' => 'OPTION_3', 'label' => 'Option-3'],
        ],
        'planOptionsSynonyms' => [
            'option 1' => 'Option-1',
            'option1' => 'Option-1',
            'option-1' => 'Option-1',
            'option 2' => 'Option-2',
            'option2' => 'Option-2',
            'option-2' => 'Option-2',
            'option 3' => 'Option-3',
            'option3' => 'Option-3',
            'option-3' => 'Option-3',
        ],

        'beneficiaryCategories' => [
            ['id' => 1, 'code' => 'PENSIONER', 'label' => 'Pensioner'],
            ['id' => 2, 'code' => 'FAMILY_PENSIONER', 'label' => 'Family Pensioner'],
            ['id' => 3, 'code' => 'NPS_PENSIONER', 'label' => 'NPS Pensioner'],
        ],
        'beneficiaryCategoriesSynonyms' => [
            'pensioners' => 'Pensioner',
            'family pensioners' => 'Family Pensioner',
            'family pensioner' => 'Family Pensioner',
            'family' => 'Family Pensioner',
            'nps' => 'NPS Pensioner',
            'nps pensioners' => 'NPS Pensioner',
        ],

        'genders' => [
            ['id' => 'MALE', 'code' => 'MALE', 'label' => 'Male'],
            ['id' => 'FEMALE', 'code' => 'FEMALE', 'label' => 'Female'],
            ['id' => 'TRANSGENDER', 'code' => 'TRANSGENDER', 'label' => 'Transgender'],
        ],
        'gendersSynonyms' => [
            'male' => 'Male',
            'm' => 'Male',
            'female' => 'Female',
            'f' => 'Female',
            'transgender' => 'Transgender',
            't' => 'Transgender',
            'others' => 'Transgender',
        ],

        'raos' => [
            ['id' => 1, 'code' => 'COG_AND_HS_JABALPUR', 'label' => 'COG & HS, Jabalpur'],
            ['id' => 2, 'code' => 'REGIONAL_ACCOUNT_OFFICE_RAO_STPS_SARNI', 'label' => 'Regional Account Office (RAO), STPS, Sarni'],
            ['id' => 3, 'code' => 'REGIONAL_ACCOUNT_OFFICE_RAO_SGTPS_BIRSINGHPUR', 'label' => 'Regional Account Office (RAO), SGTPS, Birsinghpur'],
            ['id' => 4, 'code' => 'REGIONAL_ACCOUNT_OFFICE_RAO_ATPS_CHACHAI', 'label' => 'Regional Account Office (RAO), ATPS, Chachai'],
            ['id' => 5, 'code' => 'REGIONAL_ACCOUNT_OFFICE_RAO_SSTPP_DONGALIA_KHANDWA', 'label' => 'Regional Account Office (RAO), SSTPP, Dongalia, Khandwa'],
            ['id' => 6, 'code' => 'REGIONAL_ACCOUNT_OFFICE_RAO_THC_SIRMOUR', 'label' => 'Regional Account Office (RAO), THC, Sirmour'],
            ['id' => 900, 'code' => 'OTHER', 'label' => 'Other'],
        ],
        'raosSynonyms' => [
            'rao-other' => 'Other',
            'other rao' => 'Other',
            'rao other' => 'Other',
            'regional account office other' => 'Other',
            'regional account office (rao) other' => 'Other',
            'regional account office rao stps sarni' => 'Regional Account Office (RAO), STPS, Sarni',
            'regional account office rao sgtps birsinghpur' => 'Regional Account Office (RAO), SGTPS, Birsinghpur',
            'regional account office rao atps chachai' => 'Regional Account Office (RAO), ATPS, Chachai',
            'regional account office rao sstpp dongalia khandwa' => 'Regional Account Office (RAO), SSTPP, Dongalia, Khandwa',
            'regional account office rao thc sirmour' => 'Regional Account Office (RAO), THC, Sirmour',
        ],

        'retirementOffices' => [
            ['id' => 1, 'code' => 'AMARKANTAK_THERMAL_POWER_STATION_MPPGCL_CHACHAI', 'label' => 'Amarkantak Thermal Power Station, MPPGCL, Chachai'],
            ['id' => 2, 'code' => 'SATPUDA_THERMAL_POWER_STATION_MPPGCL_SARNI', 'label' => 'Satpuda Thermal Power Station, MPPGCL, Sarni'],
            ['id' => 3, 'code' => 'SANJAY_GANDHI_THERMAL_POWER_STATIONS_MPPGCL_BIRSIN', 'label' => 'Sanjay Gandhi Thermal Power Stations, MPPGCL, Birsinghpur'],
            ['id' => 4, 'code' => 'SHREE_SINGAJI_THERMAL_POWER_PROJECTS_MPPGCL_KHANDW', 'label' => 'Shree Singaji Thermal Power Projects, MPPGCL, Khandwa'],
            ['id' => 5, 'code' => 'ADDL_CE_O_AND_M_TONS_HYDEL_COMPLEX_MPPGCL_SIRMOUR', 'label' => 'Addl. CE (O&M) Tons Hydel Complex, MPPGCL, Sirmour'],
            ['id' => 6, 'code' => 'SE_O_AND_M_TONS_HYDEL_COMPLEX_MPPGCL_SIRMOUR', 'label' => 'SE (O&M) Tons Hydel Complex, MPPGCL, Sirmour'],
            ['id' => 7, 'code' => 'SE_O_AND_M_BANSAGAR_II_MPPGCL_SILPARA', 'label' => 'SE (O&M) Bansagar - II, MPPGCL, Silpara'],
            ['id' => 8, 'code' => 'SE_O_AND_M_BANSAGAR_IV_MPPGCL_JHINNA', 'label' => 'SE (O&M) Bansagar - IV, MPPGCL, Jhinna'],
            ['id' => 9, 'code' => 'SE_O_AND_M_BANSAGAR_III_MPPGCL_DEOLOND', 'label' => 'SE (O&M) Bansagar - III, MPPGCL, Deolond'],
            ['id' => 10, 'code' => 'GANDHISAGAR_HYDEL_POWER_STATIONS_MPPGCL_GANDHISAGA', 'label' => 'Gandhisagar Hydel Power Stations, MPPGCL, Gandhisagar'],
            ['id' => 11, 'code' => 'PENCH_HYDEL_POWER_STATIONS_MPPGCL_TOTLADOH', 'label' => 'Pench Hydel Power Stations, MPPGCL, Totladoh'],
            ['id' => 12, 'code' => 'RANI_AWANTI_BAI_SAGAR_HYDEL_POWER_STATIONS_MPPGCL_', 'label' => 'Rani Awanti Bai Sagar Hydel Power Stations, MPPGCL, Barginagar'],
            ['id' => 13, 'code' => 'BANSAGAR_TONS_MPPGCL_SIRMOUR', 'label' => 'Bansagar Tons, MPPGCL, Sirmour'],
            ['id' => 14, 'code' => 'BIRSINGHPUR_HYDEL_POWER_STATIONS_MPPGCL_BIRSINGHPU', 'label' => 'Birsinghpur Hydel Power Stations, MPPGCL, Birsinghpur'],
            ['id' => 15, 'code' => 'RAJGHAT_HYDEL_POWER_STATIONS_MPPGCL_CHANDERI', 'label' => 'Rajghat Hydel Power Stations, MPPGCL, Chanderi'],
            ['id' => 16, 'code' => 'MADHIKHEDA_HYDEL_POWER_STATIONS_MPPGCL_SHIVPURI', 'label' => 'Madhikheda Hydel Power Stations, MPPGCL, Shivpuri'],
            ['id' => 17, 'code' => 'ED_ENGINEERING_MPPGCL_JABALPUR', 'label' => 'ED (Engineering), MPPGCL, Jabalpur'],
            ['id' => 18, 'code' => 'CE_FUEL_MANAGEMENT_MPPGCL_JABALPUR', 'label' => 'CE (Fuel Management), MPPGCL, Jabalpur'],
            ['id' => 19, 'code' => 'CE_CIVIL_ENGINEERING_MPPGCL_JABALPUR', 'label' => 'CE (Civil Engineering), MPPGCL, Jabalpur'],
            ['id' => 20, 'code' => 'CE_R_AND_M_MPPGCL_JABALPUR', 'label' => 'CE (R&M), MPPGCL, Jabalpur'],
            ['id' => 21, 'code' => 'CE_CORPORATE_SERVICES_MPPGCL_JABALPUR', 'label' => 'CE (Corporate Services), MPPGCL, Jabalpur'],
            ['id' => 22, 'code' => 'ED_HR_AND_A_MPPGCL_JABALPUR', 'label' => 'ED (HR&A), MPPGCL, Jabalpur'],
            ['id' => 23, 'code' => 'ED_O_AND_M_GEN_MPPGCL_JABALPUR', 'label' => 'ED (O&M:Gen), MPPGCL, Jabalpur'],
            ['id' => 24, 'code' => 'ED_PRG_MPPGCL_JABALPUR', 'label' => 'ED (PRG), MPPGCL, Jabalpur'],
            ['id' => 25, 'code' => 'CE_O_AND_M_HYDEL_MPPGCL_JABALPUR', 'label' => 'CE (O&M:Hydel), MPPGCL, Jabalpur'],
            ['id' => 26, 'code' => 'ED_MM_MPPGCL_JABALPUR', 'label' => 'ED (MM), MPPGCL, Jabalpur'],
            ['id' => 27, 'code' => 'ADDL_CE_GEN_STORES_MPPGCL_JABALPUR', 'label' => 'Addl. CE (Gen. Stores), MPPGCL, Jabalpur'],
            ['id' => 28, 'code' => 'CHIEF_FINANCIAL_OFFICER_MPPGCL_JABALPUR', 'label' => 'Chief Financial Officer, MPPGCL, Jabalpur'],
            ['id' => 29, 'code' => 'CHIEF_SECURITY_OFFICER_MPPGCL_JABALPUR', 'label' => 'Chief Security Officer, MPPGCL, Jabalpur'],
            ['id' => 30, 'code' => 'JOINT_DIRECTOR_COG_AND_HS_MPPGCL_JABALPUR', 'label' => 'Joint Director (COG&HS), MPPGCL, Jabalpur'],
            ['id' => 31, 'code' => 'SE_CIVIL_SI_AND_HM_MPPGCL_JABALPUR', 'label' => 'SE (Civil:SI&HM), MPPGCL, Jabalpur'],
            ['id' => 32, 'code' => 'DGM_INVESTIGATION_MPPGCL_JABALPUR', 'label' => 'DGM (Investigation), MPPGCL, Jabalpur'],
            ['id' => 900, 'code' => 'OTHER', 'label' => 'Other'],
        ],
        'retirementOfficesSynonyms' => [
            'ro-other' => 'Other',
            'other retirement office' => 'Other',
            'retirement office other' => 'Other',
            'retirement office (other)' => 'Other',
        ],

        'raoRetirementMap' => [
            'COG_AND_HS_JABALPUR' => [
                'GANDHISAGAR_HYDEL_POWER_STATIONS_MPPGCL_GANDHISAGA',
                'PENCH_HYDEL_POWER_STATIONS_MPPGCL_TOTLADOH',
                'RANI_AWANTI_BAI_SAGAR_HYDEL_POWER_STATIONS_MPPGCL_',
                'BANSAGAR_TONS_MPPGCL_SIRMOUR',
                'RAJGHAT_HYDEL_POWER_STATIONS_MPPGCL_CHANDERI',
                'MADHIKHEDA_HYDEL_POWER_STATIONS_MPPGCL_SHIVPURI',
                'ED_ENGINEERING_MPPGCL_JABALPUR',
                'CE_FUEL_MANAGEMENT_MPPGCL_JABALPUR',
                'CE_CIVIL_ENGINEERING_MPPGCL_JABALPUR',
                'CE_R_AND_M_MPPGCL_JABALPUR',
                'CE_CORPORATE_SERVICES_MPPGCL_JABALPUR',
                'ED_HR_AND_A_MPPGCL_JABALPUR',
                'ED_O_AND_M_GEN_MPPGCL_JABALPUR',
                'ED_PRG_MPPGCL_JABALPUR',
                'CE_O_AND_M_HYDEL_MPPGCL_JABALPUR',
                'ED_MM_MPPGCL_JABALPUR',
                'ADDL_CE_GEN_STORES_MPPGCL_JABALPUR',
                'CHIEF_FINANCIAL_OFFICER_MPPGCL_JABALPUR',
                'CHIEF_SECURITY_OFFICER_MPPGCL_JABALPUR',
                'JOINT_DIRECTOR_COG_AND_HS_MPPGCL_JABALPUR',
                'SE_CIVIL_SI_AND_HM_MPPGCL_JABALPUR',
                'DGM_INVESTIGATION_MPPGCL_JABALPUR',
            ],
            'REGIONAL_ACCOUNT_OFFICE_RAO_STPS_SARNI' => [
                'SATPUDA_THERMAL_POWER_STATION_MPPGCL_SARNI',
            ],
            'REGIONAL_ACCOUNT_OFFICE_RAO_SGTPS_BIRSINGHPUR' => [
                'SANJAY_GANDHI_THERMAL_POWER_STATIONS_MPPGCL_BIRSIN',
                'BIRSINGHPUR_HYDEL_POWER_STATIONS_MPPGCL_BIRSINGHPU',
            ],
            'REGIONAL_ACCOUNT_OFFICE_RAO_ATPS_CHACHAI' => [
                'AMARKANTAK_THERMAL_POWER_STATION_MPPGCL_CHACHAI',
            ],
            'REGIONAL_ACCOUNT_OFFICE_RAO_SSTPP_DONGALIA_KHANDWA' => [
                'SHREE_SINGAJI_THERMAL_POWER_PROJECTS_MPPGCL_KHANDW',
            ],
            'REGIONAL_ACCOUNT_OFFICE_RAO_THC_SIRMOUR' => [
                'ADDL_CE_O_AND_M_TONS_HYDEL_COMPLEX_MPPGCL_SIRMOUR',
                'SE_O_AND_M_TONS_HYDEL_COMPLEX_MPPGCL_SIRMOUR',
                'SE_O_AND_M_BANSAGAR_II_MPPGCL_SILPARA',
                'SE_O_AND_M_BANSAGAR_IV_MPPGCL_JHINNA',
                'SE_O_AND_M_BANSAGAR_III_MPPGCL_DEOLOND',
            ],
        ],

        'designations' => [
            ['id' => 1, 'code' => 'ADDL_CHIEF_ENGINEER_CIVIL', 'label' => 'Addl. Chief Engineer (Civil)'],
            ['id' => 2, 'code' => 'ADDL_CHIEF_ENGINEER_GEN', 'label' => 'Addl. Chief Engineer (Gen)'],
            ['id' => 3, 'code' => 'ADDL_CHIEF_MEDICAL_OFFICER', 'label' => 'Addl. Chief Medical Officer'],
            ['id' => 4, 'code' => 'ADDL_DIRECTOR', 'label' => 'Addl. Director'],
            ['id' => 5, 'code' => 'ASSISTANT_ENGINEER_CIVIL', 'label' => 'Assistant Engineer (Civil)'],
            ['id' => 6, 'code' => 'ASSISTANT_ENGINEER_GEN', 'label' => 'Assistant Engineer (Gen)'],
            ['id' => 7, 'code' => 'ASSISTANT_CHIEF_MEDICAL_OFFICER', 'label' => 'Assistant Chief Medical Officer'],
            ['id' => 8, 'code' => 'CHIEF_CHEMIST', 'label' => 'Chief Chemist'],
            ['id' => 9, 'code' => 'CHIEF_ENGINEER_GEN', 'label' => 'Chief Engineer (Gen)'],
            ['id' => 10, 'code' => 'CHIEF_MEDICAL_OFFICER', 'label' => 'Chief Medical Officer'],
            ['id' => 11, 'code' => 'CHIEF_SAFETY_OFFICER_EE_GEN', 'label' => 'Chief Safety Officer/EE (Gen)'],
            ['id' => 12, 'code' => 'CHIEF_SECURITY_OFFICER', 'label' => 'Chief Security Officer'],
            ['id' => 13, 'code' => 'COMPANY_SECRETARY', 'label' => 'Company Secretary'],
            ['id' => 14, 'code' => 'DEPUTY_SECRETARY', 'label' => 'Deputy Secretary'],
            ['id' => 15, 'code' => 'DGM_HR', 'label' => 'DGM (HR)'],
            ['id' => 16, 'code' => 'DGM_INVESTIGATIONS', 'label' => 'DGM (Investigations)'],
            ['id' => 17, 'code' => 'DIRECTOR', 'label' => 'Director'],
            ['id' => 18, 'code' => 'DY_DIRECTOR_SR_A_O', 'label' => 'Dy. Director/ Sr. A.O'],
            ['id' => 19, 'code' => 'DY_CGM_HR', 'label' => 'Dy.CGM (HR)'],
            ['id' => 20, 'code' => 'ED_DIRECTOR_CFO', 'label' => 'ED/ Director (CFO)'],
            ['id' => 21, 'code' => 'ED_CHIEF_ENGINEER_CIVIL', 'label' => 'ED/Chief Engineer (Civil)'],
            ['id' => 22, 'code' => 'EXECUTIVE_DIRECTOR_GEN', 'label' => 'Executive Director (Gen)'],
            ['id' => 23, 'code' => 'EXECUTIVE_DIRECTOR_HR', 'label' => 'Executive Director (HR)'],
            ['id' => 24, 'code' => 'EXECUTIVE_ENGINEER_CIVIL', 'label' => 'Executive Engineer (Civil)'],
            ['id' => 25, 'code' => 'EXECUTIVE_ENGINEER_GEN', 'label' => 'Executive Engineer (Gen)'],
            ['id' => 26, 'code' => 'GM_HR', 'label' => 'GM (HR)'],
            ['id' => 27, 'code' => 'INDUSTRIAL_RELATIONS_OFFICER', 'label' => 'Industrial Relations Officer'],
            ['id' => 28, 'code' => 'JOINT_SECRETARY', 'label' => 'Joint Secretary'],
            ['id' => 29, 'code' => 'JT_DIRECTOR', 'label' => 'Jt. Director'],
            ['id' => 30, 'code' => 'MANAGING_DIRECTOR', 'label' => 'Managing Director'],
            ['id' => 31, 'code' => 'RETIRED', 'label' => 'Retired'],
            ['id' => 32, 'code' => 'SENIOR_ADMINISTRATIVE_OFFICER', 'label' => 'Senior Administrative Officer'],
            ['id' => 33, 'code' => 'SENIOR_SYSTEM_ANALYST', 'label' => 'Senior System Analyst'],
            ['id' => 34, 'code' => 'SR_CHEMIST', 'label' => 'Sr. Chemist'],
            ['id' => 35, 'code' => 'SR_CHIEF_CHEMIST', 'label' => 'Sr. Chief Chemist'],
            ['id' => 36, 'code' => 'SR_FIRE_OFFICER', 'label' => 'Sr. Fire Officer'],
            ['id' => 37, 'code' => 'SR_GEOLOGIST', 'label' => 'Sr. Geologist'],
            ['id' => 38, 'code' => 'SR_LAW_OFFICER', 'label' => 'Sr. Law officer'],
            ['id' => 39, 'code' => 'SR_MEDICAL_OFFICER', 'label' => 'Sr. Medical Officer'],
            ['id' => 40, 'code' => 'SR_SECURITY_OFFICER', 'label' => 'Sr. Security Officer'],
            ['id' => 41, 'code' => 'SR_WELFARE_OFFICER', 'label' => 'Sr. Welfare Officer'],
            ['id' => 42, 'code' => 'STAFF_OFFICER', 'label' => 'Staff Officer'],
            ['id' => 43, 'code' => 'SUPERINTENDING_ENGINEER_CIVIL', 'label' => 'Superintending Engineer (Civil)'],
            ['id' => 44, 'code' => 'SUPERINTENDING_ENGINEER_GEN', 'label' => 'Superintending Engineer (Gen)'],
            ['id' => 45, 'code' => 'ACCOUNTS_OFFICER', 'label' => 'Accounts Officer'],
            ['id' => 46, 'code' => 'ADMINISTRATIVE_OFFICER', 'label' => 'Administrative Officer'],
            ['id' => 47, 'code' => 'ASSISTANT_GEOLOGIST', 'label' => 'Assistant Geologist'],
            ['id' => 48, 'code' => 'CHIEF_STOCK_VERIFIER', 'label' => 'Chief Stock Verifier'],
            ['id' => 49, 'code' => 'EDP_OFFICER', 'label' => 'EDP Officer'],
            ['id' => 50, 'code' => 'ESTATE_OFFICER', 'label' => 'Estate Officer'],
            ['id' => 51, 'code' => 'FIRE_OFFICER', 'label' => 'Fire Officer'],
            ['id' => 52, 'code' => 'HORTICULTURIST', 'label' => 'Horticulturist'],
            ['id' => 53, 'code' => 'LAW_OFFICER', 'label' => 'Law Officer'],
            ['id' => 54, 'code' => 'MANAGER_HR_PERSONNEL_OFFICER', 'label' => 'Manager (HR)/ Personnel Officer'],
            ['id' => 55, 'code' => 'MEDICAL_OFFICER', 'label' => 'Medical Officer'],
            ['id' => 56, 'code' => 'PRIVATE_SECRETARY', 'label' => 'Private Secretary'],
            ['id' => 57, 'code' => 'PROGRAMMER', 'label' => 'Programmer'],
            ['id' => 58, 'code' => 'PUBLICITY_OFFICER', 'label' => 'Publicity Officer'],
            ['id' => 59, 'code' => 'SAFETY_OFFICER_AE_GEN', 'label' => 'Safety Officer/ AE (Gen)'],
            ['id' => 60, 'code' => 'SECURITY_OFFICER', 'label' => 'Security Officer'],
            ['id' => 61, 'code' => 'SHIFT_CHEMIST', 'label' => 'Shift Chemist'],
            ['id' => 62, 'code' => 'SR_MAINTENANCE_SHIFT_OFFICER', 'label' => 'Sr.Maintenance/Shift Officer'],
            ['id' => 63, 'code' => 'SYSTEM_ANALYST', 'label' => 'System Analyst'],
            ['id' => 64, 'code' => 'TECHNICAL_OFFICER', 'label' => 'Technical Officer'],
            ['id' => 65, 'code' => 'WELFARE_OFFICER', 'label' => 'Welfare Officer'],
            ['id' => 66, 'code' => 'ANM_MIDWIFE', 'label' => 'ANM (Midwife)'],
            ['id' => 67, 'code' => 'ASSISTANT_DRILLER', 'label' => 'Assistant Driller'],
            ['id' => 68, 'code' => 'ASSISTANT_FIRE_OFFICER', 'label' => 'Assistant Fire Officer'],
            ['id' => 69, 'code' => 'ASST_DRAFTSMAN_CIVIL', 'label' => 'Asst. Draftsman (Civil)'],
            ['id' => 70, 'code' => 'ASST_DRAFTSMAN_ELECTRICAL', 'label' => 'Asst. Draftsman (Electrical)'],
            ['id' => 71, 'code' => 'BLUE_PRINTER', 'label' => 'Blue Printer'],
            ['id' => 72, 'code' => 'CIVIL_ASST', 'label' => 'Civil Asst.'],
            ['id' => 73, 'code' => 'CIVIL_SUPERVISOR', 'label' => 'Civil Supervisor'],
            ['id' => 74, 'code' => 'DARK_ROOK_ATTENDANT', 'label' => 'Dark Rook Attendant'],
            ['id' => 75, 'code' => 'DIPLOMA_TRAINEE_DT', 'label' => 'Diploma Trainee(DT)'],
            ['id' => 76, 'code' => 'DRAFTSMAN_CIVIL', 'label' => 'Draftsman (Civil)'],
            ['id' => 77, 'code' => 'DRAFTSMAN_ELECTRICAL', 'label' => 'Draftsman (Electrical)'],
            ['id' => 78, 'code' => 'DRESSER', 'label' => 'Dresser'],
            ['id' => 79, 'code' => 'ECG_TECHNICIAN', 'label' => 'ECG Technician'],
            ['id' => 80, 'code' => 'FIRE_TENDER_DRIVER', 'label' => 'Fire Tender Driver'],
            ['id' => 81, 'code' => 'FIREMAN', 'label' => 'Fireman'],
            ['id' => 82, 'code' => 'HEAD_DRAFTSMAN_CIVIL', 'label' => 'Head Draftsman (Civil)'],
            ['id' => 83, 'code' => 'HEAD_DRAFTSMAN_ELECTRICAL', 'label' => 'Head Draftsman (Electrical)'],
            ['id' => 84, 'code' => 'HEAD_SECURITY_GUARD', 'label' => 'Head Security Guard'],
            ['id' => 85, 'code' => 'HEAD_STORE_KEEPER', 'label' => 'Head Store Keeper'],
            ['id' => 86, 'code' => 'JR_STENO', 'label' => 'Jr. Steno'],
            ['id' => 87, 'code' => 'JUNIOR_ENGINEER_CIVIL', 'label' => 'Junior Engineer (Civil)'],
            ['id' => 88, 'code' => 'JUNIOR_ENGINEER_PLANT', 'label' => 'Junior Engineer (Plant)'],
            ['id' => 89, 'code' => 'LAB_TECHNICIAN', 'label' => 'Lab Technician'],
            ['id' => 90, 'code' => 'LAW_ASSISTANT', 'label' => 'Law Assistant'],
            ['id' => 91, 'code' => 'LEADING_FIREMAN', 'label' => 'Leading Fireman'],
            ['id' => 92, 'code' => 'MOTOR_DRIVER', 'label' => 'Motor Driver'],
            ['id' => 93, 'code' => 'NURSING_SISTER', 'label' => 'Nursing Sister'],
            ['id' => 94, 'code' => 'OFFICE_ASST_GR_I', 'label' => 'Office Asst. Gr. I'],
            ['id' => 95, 'code' => 'OFFICE_ASST_GR_II', 'label' => 'Office Asst. Gr. II'],
            ['id' => 96, 'code' => 'OFFICE_ASST_GR_III', 'label' => 'Office Asst. Gr. III'],
            ['id' => 97, 'code' => 'PATWARI', 'label' => 'Patwari'],
            ['id' => 98, 'code' => 'PERSONAL_ASSISTANT', 'label' => 'Personal Assistant'],
            ['id' => 99, 'code' => 'PHARMACIST_COMPOUNDER', 'label' => 'Pharmacist (Compounder)'],
            ['id' => 100, 'code' => 'PHYSIOTHERAPIST', 'label' => 'Physiotherapist'],
            ['id' => 101, 'code' => 'PLANT_ASSISTANT', 'label' => 'Plant Assistant'],
            ['id' => 102, 'code' => 'PLANT_SUPERVISOR', 'label' => 'Plant Supervisor'],
            ['id' => 103, 'code' => 'PUBLICITY_ASSISTANT', 'label' => 'Publicity Assistant'],
            ['id' => 104, 'code' => 'RADIOGRAPHER', 'label' => 'Radiographer'],
            ['id' => 105, 'code' => 'SANITARY_INSPECTOR', 'label' => 'Sanitary Inspector'],
            ['id' => 106, 'code' => 'SECTION_OFFICER', 'label' => 'Section Officer'],
            ['id' => 107, 'code' => 'SECURITY_ASSTT_SUB_INSPECTOR', 'label' => 'Security Asstt. Sub Inspector'],
            ['id' => 108, 'code' => 'SECURITY_INSPECTOR', 'label' => 'Security Inspector'],
            ['id' => 109, 'code' => 'SECURITY_SUB_INSPECTOR', 'label' => 'Security Sub Inspector'],
            ['id' => 110, 'code' => 'SENIOR_DRAFTSMAN_CIVIL', 'label' => 'Senior Draftsman (Civil)'],
            ['id' => 111, 'code' => 'SENIOR_DRAFTSMAN_ELECTRICAL', 'label' => 'Senior Draftsman (Electrical)'],
            ['id' => 112, 'code' => 'SR_CIVIL_ASST', 'label' => 'Sr. Civil Asst.'],
            ['id' => 113, 'code' => 'SR_CIVIL_SUPERVISOR', 'label' => 'Sr. Civil Supervisor'],
            ['id' => 114, 'code' => 'SR_PLANT_ASSISTANT', 'label' => 'Sr. Plant Assistant'],
            ['id' => 115, 'code' => 'SR_PLANT_SUPERVISOR', 'label' => 'Sr. Plant Supervisor'],
            ['id' => 116, 'code' => 'SR_STENO', 'label' => 'Sr. Steno'],
            ['id' => 117, 'code' => 'SR_TESTING_ASSISTANT', 'label' => 'Sr. Testing Assistant'],
            ['id' => 118, 'code' => 'STAFF_NURSE', 'label' => 'Staff Nurse'],
            ['id' => 119, 'code' => 'STENO_TYPIST', 'label' => 'Steno Typist'],
            ['id' => 120, 'code' => 'STOCK_VERIFIER', 'label' => 'Stock Verifier'],
            ['id' => 121, 'code' => 'STORE_ASSISTANT', 'label' => 'Store Assistant'],
            ['id' => 122, 'code' => 'STORE_KEEPER_GR_II', 'label' => 'Store Keeper Gr. II'],
            ['id' => 123, 'code' => 'SUB_FIRE_OFFICER', 'label' => 'Sub Fire Officer'],
            ['id' => 124, 'code' => 'TECHNICAL_APPRENTICE_TA', 'label' => 'Technical Apprentice(TA)'],
            ['id' => 125, 'code' => 'TELEPHONE_OPERATOR', 'label' => 'Telephone Operator'],
            ['id' => 126, 'code' => 'TELEPRINTER_OPERATOR', 'label' => 'Teleprinter Operator'],
            ['id' => 127, 'code' => 'TELEX_OPERATOR', 'label' => 'Telex Operator'],
            ['id' => 128, 'code' => 'TESTING_ASST', 'label' => 'Testing Asst.'],
            ['id' => 129, 'code' => 'WELFARE_ASSISTANT', 'label' => 'Welfare Assistant'],
            ['id' => 130, 'code' => 'ASSISTANT_DRESSER', 'label' => 'Assistant Dresser'],
            ['id' => 131, 'code' => 'CIVIL_ATTENDANT', 'label' => 'Civil Attendant'],
            ['id' => 132, 'code' => 'CLEANER', 'label' => 'Cleaner'],
            ['id' => 133, 'code' => 'COOK', 'label' => 'Cook'],
            ['id' => 134, 'code' => 'COURIER', 'label' => 'Courier'],
            ['id' => 135, 'code' => 'DAFTARI', 'label' => 'Daftari'],
            ['id' => 136, 'code' => 'DRAWING_OFFICE_ASST_GR_I_CIVIL', 'label' => 'Drawing Office Asst. Gr-I (Civil)'],
            ['id' => 137, 'code' => 'DRAWING_OFFICE_ASST_GR_I_ELEC', 'label' => 'Drawing Office Asst. Gr-I (Elec)'],
            ['id' => 138, 'code' => 'FARRASH', 'label' => 'Farrash'],
            ['id' => 139, 'code' => 'GARDENER', 'label' => 'Gardener'],
            ['id' => 140, 'code' => 'JAMADAR', 'label' => 'Jamadar'],
            ['id' => 141, 'code' => 'KHANSAMA', 'label' => 'Khansama'],
            ['id' => 142, 'code' => 'LAB_ATTENDANT_WARD_BOY', 'label' => 'Lab Attendant / Ward Boy'],
            ['id' => 143, 'code' => 'LADY_ATTENDANT_WARD_AYAH', 'label' => 'Lady Attendant / Ward Ayah'],
            ['id' => 144, 'code' => 'LINE_ATTENDANT', 'label' => 'Line Attendant'],
            ['id' => 145, 'code' => 'ORDERLY_PEON', 'label' => 'Orderly Peon'],
            ['id' => 146, 'code' => 'PEON', 'label' => 'Peon'],
            ['id' => 147, 'code' => 'PLANT_ATTENDANT', 'label' => 'Plant Attendant'],
            ['id' => 148, 'code' => 'SECURITY_GUARD', 'label' => 'Security Guard'],
            ['id' => 149, 'code' => 'SENIOR_LINE_ATTEND_LINE_ATTENDANT', 'label' => 'Senior Line Attend / Line Attendant'],
            ['id' => 150, 'code' => 'SR_CIVIL_ATTENDANT', 'label' => 'Sr. Civil Attendant'],
            ['id' => 151, 'code' => 'SR_PLANT_ATTENDANT', 'label' => 'Sr. Plant Attendant'],
            ['id' => 152, 'code' => 'SR_SECURITY_GUARD', 'label' => 'Sr. Security Guard'],
            ['id' => 153, 'code' => 'SWEEPER', 'label' => 'Sweeper'],
            ['id' => 154, 'code' => 'UNSKILLED_LABOUR_GEN_NMR', 'label' => 'Unskilled Labour (Gen)/ NMR'],
            ['id' => 155, 'code' => 'WAITER_HELPER_TO_KHANSAMA', 'label' => 'Waiter (Helper to Khansama)'],
            ['id' => 900, 'code' => 'OTHER', 'label' => 'Other'],
        ],
        'designationsSynonyms' => [
            'desg-other' => 'Other',
            'other designation' => 'Other',
            'designation other' => 'Other',
        ],

        'banks' => [
            ['id' => 1, 'code' => 'STATE_BANK_OF_INDIA_', 'label' => 'State Bank of India (SBI)'],
            ['id' => 2, 'code' => 'UNION_BANK_OF_INDIA_', 'label' => 'Union Bank of India (UBI)'],
            ['id' => 900, 'code' => 'OTHER', 'label' => 'Other'],
        ],
        'banksSynonyms' => [
            'bank-other' => 'Other',
            'other bank' => 'Other',
            'sbi' => 'State Bank of India (SBI)',
            'state bank of india' => 'State Bank of India (SBI)',
            'state bank' => 'State Bank of India (SBI)',
            'ubi' => 'Union Bank of India (UBI)',
            'union bank' => 'Union Bank of India (UBI)',
            'union bank of india' => 'Union Bank of India (UBI)',
        ],
        'bankSources' => [
            ['id' => 1, 'code' => 'STATE_BANK_OF_INDIA_', 'label' => 'State Bank of India (SBI)'],
            ['id' => 2, 'code' => 'UNION_BANK_OF_INDIA_', 'label' => 'Union Bank of India (UBI)'],
            ['id' => 900, 'code' => 'OTHER', 'label' => 'Other'],
        ],
        'bankServicing' => [
            ['id' => 1, 'code' => 'STATE_BANK_OF_INDIA_', 'label' => 'State Bank of India (SBI)'],
            ['id' => 2, 'code' => 'UNION_BANK_OF_INDIA_', 'label' => 'Union Bank of India (UBI)'],
            ['id' => 900, 'code' => 'OTHER', 'label' => 'Other'],
        ],

        'bloodGroups' => [
            ['id' => 1, 'label' => 'A+'],
            ['id' => 2, 'label' => 'A-'],
            ['id' => 3, 'label' => 'B+'],
            ['id' => 4, 'label' => 'B-'],
            ['id' => 5, 'label' => 'AB+'],
            ['id' => 6, 'label' => 'AB-'],
            ['id' => 7, 'label' => 'O+'],
            ['id' => 8, 'label' => 'O-'],
        ],
        'bloodGroupsSynonyms' => [
            'a positive' => 'A+',
            'a negative' => 'A-',
            'b positive' => 'B+',
            'b negative' => 'B-',
            'ab positive' => 'AB+',
            'ab negative' => 'AB-',
            'o positive' => 'O+',
            'o negative' => 'O-',
        ],

        'states' => [
            ['id' => 1, 'label' => 'ANDHRA PRADESH', 'flag' => 0],
            ['id' => 2, 'label' => 'ASSAM', 'flag' => 0],
            ['id' => 3, 'label' => 'BIHAR', 'flag' => 0],
            ['id' => 4, 'label' => 'CHANDIGARH', 'flag' => 0],
            ['id' => 5, 'label' => 'CHHATTISGARH', 'flag' => 1],
            ['id' => 6, 'label' => 'DELHI', 'flag' => 0],
            ['id' => 7, 'label' => 'GOA', 'flag' => 0],
            ['id' => 8, 'label' => 'GUJARAT', 'flag' => 1],
            ['id' => 9, 'label' => 'HARYANA', 'flag' => 0],
            ['id' => 10, 'label' => 'HIMACHAL PRADESH', 'flag' => 0],
            ['id' => 12, 'label' => 'JHARKHAND', 'flag' => 0],
            ['id' => 13, 'label' => 'KARNATAKA', 'flag' => 0],
            ['id' => 14, 'label' => 'KERALA', 'flag' => 0],
            ['id' => 15, 'label' => 'MADHYA PRADESH', 'flag' => 1],
            ['id' => 16, 'label' => 'MAHARASHTRA', 'flag' => 1],
            ['id' => 17, 'label' => 'MEGHALAYA', 'flag' => 0],
            ['id' => 20, 'label' => 'PUNJAB', 'flag' => 0],
            ['id' => 21, 'label' => 'RAJASTHAN', 'flag' => 1],
            ['id' => 23, 'label' => 'SIKKIM', 'flag' => 0],
            ['id' => 24, 'label' => 'TAMIL NADU', 'flag' => 0],
            ['id' => 25, 'label' => 'TELANGANA', 'flag' => 0],
            ['id' => 26, 'label' => 'TRIPURA', 'flag' => 0],
            ['id' => 27, 'label' => 'UTTAR PRADESH', 'flag' => 1],
            ['id' => 28, 'label' => 'UTTARAKHAND', 'flag' => 0],
            ['id' => 29, 'label' => 'WEST BENGAL', 'flag' => 0],
            ['id' => 30, 'label' => 'ARUNACHAL PRADESH', 'flag' => 0],
            ['id' => 31, 'label' => 'MANIPUR', 'flag' => 0],
            ['id' => 32, 'label' => 'MIZORAM', 'flag' => 0],
            ['id' => 33, 'label' => 'NAGALAND', 'flag' => 0],
            ['id' => 34, 'label' => 'ODISHA', 'flag' => 0],
            ['id' => 35, 'label' => 'ANDAMAN AND NICOBAR ISLANDS', 'flag' => 0],
            ['id' => 36, 'label' => 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU', 'flag' => 0],
            ['id' => 37, 'label' => 'JAMMU AND KASHMIR', 'flag' => 0],
            ['id' => 38, 'label' => 'LADAKH', 'flag' => 0],
            ['id' => 39, 'label' => 'LAKSHADWEEP', 'flag' => 0],
            ['id' => 40, 'label' => 'PUDUCHERRY', 'flag' => 0],
        ],
        'statesSynonyms' => [
            'mp' => 'MADHYA PRADESH',
            'm.p.' => 'MADHYA PRADESH',
            'm.p' => 'MADHYA PRADESH',
            'm p' => 'MADHYA PRADESH',
            'cg' => 'CHHATTISGARH',
            'c.g.' => 'CHHATTISGARH',
            'c g' => 'CHHATTISGARH',
            'up' => 'UTTAR PRADESH',
            'u.p.' => 'UTTAR PRADESH',
            'u.p' => 'UTTAR PRADESH',
            'u p' => 'UTTAR PRADESH',
            'mh' => 'MAHARASHTRA',
            'mharashtra' => 'MAHARASHTRA',
            'rajasthan state' => 'RAJASTHAN',
            'delhi ncr' => 'DELHI',
        ],
    ];
}


