<?php
$sections             = $detailSections ?? [];
$coveredDependents    = $dependentsCovered ?? [];
$otherDependents      = $dependentsNotDependent ?? [];
$referenceNumber      = $snapshot['reference_number'] ?? '-';
$companyName          = $companyName ?? ($snapshot['company_name'] ?? null);
$lastUpdatedDisplay   = $lastUpdatedDisplay ?? '-';
$generatedAtDisplay   = $generatedAtDisplay ?? '-';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: "DejaVu Sans", "Noto Sans Devanagari", sans-serif;
            font-size: 11px;
            color: #1e1e1e;
            margin: 0;
            padding: 24px;
            background: #fff;
        }
        h1, h2 {
            margin: 0 0 8px;
            color: #0c2340;
        }
        h1 {
            font-size: 22px;
        }
        h2 {
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: .5px;
        }
        .report-header {
            display: flex;
            justify-content: space-between;
            gap: 16px;
            padding-bottom: 12px;
            border-bottom: 2px solid #0c2340;
            margin-bottom: 20px;
        }
        .meta {
            font-size: 10px;
            color: #555;
            text-align: right;
        }
        .section {
            margin-bottom: 18px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        .detail-table th {
            width: 30%;
            text-align: left;
            background: #f5f7fb;
        }
        th, td {
            border: 1px solid #d7dbe8;
            padding: 6px 8px;
            vertical-align: top;
        }
        .table-note {
            font-style: italic;
            color: #666;
            margin: 0;
        }
        .dependents-table th {
            background: #0c2340;
            color: #fff;
            text-align: left;
        }
        .chip {
            display: inline-block;
            padding: 2px 6px;
            font-size: 10px;
            border-radius: 4px;
            background: #eef2ff;
            color: #1d3c78;
        }
    </style>
</head>
<body>
    <div class="report-header">
        <div>
            <h1>Beneficiary Profile</h1>
            <p>
                <strong>Reference:</strong> <?= esc($referenceNumber) ?><br>
                <?php if ($companyName): ?>
                    <strong>Company:</strong> <?= esc($companyName) ?><br>
                <?php endif; ?>
                <?php if (! empty($snapshot['beneficiary_name'])): ?>
                    <strong>Name:</strong> <?= esc($snapshot['beneficiary_name']) ?><br>
                <?php endif; ?>
            </p>
        </div>
        <div class="meta">
            <div>Last Updated: <?= esc($lastUpdatedDisplay) ?></div>
            <div>Generated By: Helpdesk</div>
            <div>Generated On: <?= esc($generatedAtDisplay) ?></div>
        </div>
    </div>

    <?php if (! empty($sections)): ?>
        <?php foreach ($sections as $section): ?>
            <section class="section">
                <h2><?= esc($section['title']) ?></h2>
                <table class="detail-table">
                    <tbody>
                        <?php foreach ($section['rows'] as $row): ?>
                            <tr>
                                <th><?= esc($row['label']) ?></th>
                                <td><?= esc($row['value'] ?? '-') ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </section>
        <?php endforeach; ?>
    <?php else: ?>
        <p class="table-note">No beneficiary details recorded.</p>
    <?php endif; ?>

    <section class="section">
        <h2>Dependents Covered</h2>
        <p class="table-note">Family members currently eligible for scheme benefits.</p>
        <?php if (! empty($coveredDependents)): ?>
            <table class="dependents-table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Relation</th>
                        <th>Status</th>
                        <th>Health Coverage</th>
                        <th>Name</th>
                        <th>Gender</th>
                        <th>Blood Group</th>
                        <th>Date of Birth</th>
                        <th>Aadhaar</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($coveredDependents as $dependent): ?>
                        <?php
                            $healthLabel = $dependent['health_label'] ?? null;
                            if ($healthLabel === null && array_key_exists('is_dependent_for_health', $dependent)) {
                                if (! empty($dependent['is_dependent_for_health'])) {
                                    $healthLabel = 'Yes';
                                } elseif (strtolower((string) ($dependent['status'] ?? '')) === 'not applicable') {
                                    $healthLabel = 'Not Applicable';
                                } elseif (strtolower((string) ($dependent['status'] ?? '')) === 'not provided') {
                                    $healthLabel = 'Not Provided';
                                } else {
                                    $healthLabel = 'No';
                                }
                            }
                        ?>
                        <tr>
                            <td><?= esc($dependent['order'] ?? '-') ?></td>
                            <td><?= esc($dependent['relation'] ?? '-') ?></td>
                            <td><?= esc($dependent['status'] ?? '-') ?></td>
                            <td><?= esc($healthLabel ?? 'Not Provided') ?></td>
                            <td><?= esc($dependent['name'] ?? '-') ?></td>
                            <td><?= esc($dependent['gender'] ?? 'Not Provided') ?></td>
                            <td><?= esc($dependent['blood_group'] ?? '-') ?></td>
                            <td><?= esc($dependent['date_of_birth'] ?? '-') ?></td>
                            <td><?= esc($dependent['aadhar_number'] ?? '-') ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <p class="table-note">No dependents are currently marked as covered.</p>
        <?php endif; ?>
    </section>

    <section class="section">
        <h2>Other Family Members</h2>
        <p class="table-note">Family members recorded for reference. Update their coverage if eligibility changes.</p>
        <?php if (! empty($otherDependents)): ?>
            <table class="dependents-table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Relation</th>
                        <th>Status</th>
                        <th>Health Coverage</th>
                        <th>Name</th>
                        <th>Gender</th>
                        <th>Blood Group</th>
                        <th>Date of Birth</th>
                        <th>Aadhaar</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($otherDependents as $dependent): ?>
                        <?php
                            $healthLabel = $dependent['health_label'] ?? null;
                            if ($healthLabel === null && array_key_exists('is_dependent_for_health', $dependent)) {
                                if (! empty($dependent['is_dependent_for_health'])) {
                                    $healthLabel = 'Yes';
                                } elseif (strtolower((string) ($dependent['status'] ?? '')) === 'not applicable') {
                                    $healthLabel = 'Not Applicable';
                                } elseif (strtolower((string) ($dependent['status'] ?? '')) === 'not provided') {
                                    $healthLabel = 'Not Provided';
                                } else {
                                    $healthLabel = 'No';
                                }
                            }
                        ?>
                        <tr>
                            <td><?= esc($dependent['order'] ?? '-') ?></td>
                            <td><?= esc($dependent['relation'] ?? '-') ?></td>
                            <td><?= esc($dependent['status'] ?? '-') ?></td>
                            <td><?= esc($healthLabel ?? 'Not Provided') ?></td>
                            <td><?= esc($dependent['name'] ?? '-') ?></td>
                            <td><?= esc($dependent['gender'] ?? 'Not Provided') ?></td>
                            <td><?= esc($dependent['blood_group'] ?? '-') ?></td>
                            <td><?= esc($dependent['date_of_birth'] ?? '-') ?></td>
                            <td><?= esc($dependent['aadhar_number'] ?? '-') ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <p class="table-note">No additional family members recorded.</p>
        <?php endif; ?>
    </section>
</body>
</html>
